name: Test mm-jsr pull request

on:
  pull_request:
    paths:
      - 'packages/mm-jsr/**.ts'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn test
        working-directory: ./packages/mm-jsr
  lib-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn build
        working-directory: ./packages/mm-jsr
