name: Test react-mm-jsr pull request

on:
  pull_request:


jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn build
      - run: yarn test
        working-directory: ./packages/react-mm-jsr
