name: Version and release mm-jsr

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of release'
        required: true

permissions:
  id-token: write # Required for trusted publishing
  contents: write # Required for updating version

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
        working-directory: ./packages/mm-jsr
  release:
    needs: unit-tests
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x' # required for trusted publishing
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - run: pnpm install
      - run: pnpm build
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "GH Actions"
      - run: pnpm version --new-version ${{ github.event.inputs.version }} --no-git-tag-version
        working-directory: ./packages/mm-jsr
      - run: git commit -a -m "[mm-jsr] v${{ github.event.inputs.version }}"
      - run: git tag v${{ github.event.inputs.version }}
      - run: cp ./README.md ./packages/mm-jsr/README.md
      - run: npm publish --no-git-checks   # we copied readme so need to disable check - we do not want to commit README though
        working-directory: ./packages/mm-jsr
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
