name: "size"

on:
  pull_request:

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses:  soanvig/size-limit-action-yarn-v2@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}