name: Deploy webpage

on:
  push:
    branches:
      - master

jobs:
  webpage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GH Actions"
          git checkout gh-pages
          git reset --hard origin/master
      - run: yarn workspace mm-jsr build
      - run: yarn workspace webpage build
      - run: yarn workspace mm-jsr docs
      - name: Copy resources
        run: |
          rm -rf ./docs
          cp -r packages/webpage/public ./docs
          cp -r packages/mm-jsr/api ./docs
      - name: Commit changes
        run: |
          git add ./docs
          git add --force ./docs/build
          git commit -m "Update webpage and docs"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
